export const ACTION_TYPE_GET_COLLECTIONS = "ACTION_TYPE_GET_COLLECTIONS";

export const ACTION_TYPE_ADD_TO_CART = "ACTION_TYPE_ADD_TO_CART";

export const ACTION_TYPE_FETCH_MOVIES_REQUEST = "ACTION_TYPE_FETCH_MOVIES_REQUEST";

export const ACTION_TYPE_FETCH_MOVIES_SUCCESS = "ACTION_TYPE_FETCH_MOVIES_SUCCESS";

export const ACTION_TYPE_FETCH_MOVIES_FAILURE = "ACTION_TYPE_FETCH_MOVIES_FAILURE";
